GET http://localhost:3000/api/blogs

###
POST http://localhost:3000/api/blogs
Content-Type: application/json

{
  "title": "What is node js?",
  "author": "Yojan Regmi",
  "url": "https://yojanregmi.com.np",
  "likes": 0
}