
GET http://localhost:3000/api/blogs

###
POST http://localhost:3000/api/blogs
Content-Type: application/json

{
  "author": "DevYojan",
  "url": "https://yojanregmi.com.np"
}

###
DELETE  http://localhost:3000/api/blogs/5ec9521ab2307ee632c050f6


###
PUT http://localhost:3000/api/blogs/5ec9534a77a5cdee643fe8d8
Content-Type: application/json

{
  "likes": 250
}


###
GET http://localhost:3000/api/users


###
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "aaa",
  "name": "Regmi"
}
